spring.application.name=integration
serenity.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjkyMjk4NzcsInN1YiI6IjRkYmQ0NDY4LTBlYzMtNDk2MS1hNjgyLTAxMjQ5MWRhMjQzYyIsInNjb3BlcyI6WyJjdXJyZW50X3VzZXI6cmVhZCJdfQ.uG1fyuadr6k0XYEXcqrZ3hAfwFYglZeDwl5acKdAhaA

spring.datasource.url= jdbc:postgresql://84.247.186.84/vectordb
spring.datasource.username= testuser
spring.datasource.password= testpwd
hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto= update
server.port=9099


spring.main.allow-bean-definition-overriding=true
spring.datasource.his.url= jdbc:mysql://54.74.190.24:3306/nyaho?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.his.username= serenity
spring.datasource.his.password= JQ0qlE@_-wp
hibernate.jdbc.lob.non_contextual_creation=true
spring.his.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.his.jpa.hibernate.ddl-auto= update
access.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwNzg5MDkxLCJqdGkiOiJhZmJjNzdhYTUxMzE0Y2U3YmUyMDE4Mjc2NmQ3OGI0YSIsInVzZXJfaWQiOjF9.NShRghP8tbx2gHuXQkF8W1gTXKSSnjFxqN-c98xzDjc